---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.18"
  name: mosquitto
data:
  mosquitto.conf: |-
    persistence false
    persistence_location /mosquitto/data/
    log_dest stdout
    password_file /mosquitto/config/accounts.conf
    acl_file /mosquitto/config/acls.conf
    listener 1883
    
  accounts.conf: |-
    
  acls.conf: |-