---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.18"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mosquitto
    spec:
      securityContext:
        {}
      containers:
        - name: mosquitto
          securityContext:
            {}
          image: "eclipse-mosquitto:2.0.18"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: mqttssl
              containerPort: 8883
              protocol: TCP
            - name: mqttws
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1883
          readinessProbe:
            httpGet:
            tcpSocket:
              port: 1883
          resources:
            {}
          volumeMounts:
          - name: config-volume
            mountPath: /mosquitto/config
          - name: mosquitto-data
            mountPath: /mosquitto/data/
            subPath: 
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data 
  volumeClaimTemplates:
    - metadata:
        name: mosquitto-data  # The name must match the volumeMounts name
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi