apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.21
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: mqttssl
              containerPort: 8883
              protocol: TCP
            - name: mqttws
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1883
          readinessProbe:
            tcpSocket:
              port: 1883
          volumeMounts:
            - name: zoneinfo
              mountPath: /etc/localtime
              subPath: America/New_York
              readOnly: true
            - name: mosquitto-pvc
              mountPath: /mosquitto/
#            - name: mosquitto-data
#              mountPath: /mosquitto/
      volumes:
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
#        - name: mosquitto-pvc
#          configMap:
#            name: mosquitto
        - name: mosquitto-pvc
          persistentVolumeClaim:
            claimName: mosquitto-pvc
 #       - name: mosquitto-data
 #         hostPath:
 #           path: /home/tpearson/hass/k8s-mosquitto
