---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.18"
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: 8883
      targetPort: mqttssl
      protocol: TCP
      name: mqttssl
    - port: 9001
      targetPort: mqttws
      protocol: TCP
      name: mqttws
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto